### ISSUE TITLE
DTO 생성

### ISSUE THREAD

**Issue by qazplm12** [ezjing/team3Project#2]
테스트
- [x] customerTp
- [x] ceoTp
- [x] reviewTp
- [x] reservationTp
- [x] questionTp

**Comment by qazplm12** [comment]
ceoTp 자바파일
[CeoTp.zip](https://github.com/ezjing/team3Project/files/11912877/CeoTp.zip)

**Comment by jeti11** [comment]
customer, reservation dto파일

[CustomerTp.zip](https://github.com/ezjing/team3Project/files/11913001/CustomerTp.zip)

**Comment by shlise77** [comment]
question, review Dto 파일입니다.

[questionDto.zip](https://github.com/ezjing/team3Project/files/11913135/questionDto.zip)
